from __future__ import annotations

from dataclasses import asdict, dataclass
import hashlib
import json
from pathlib import Path
import re
import shlex
import sys
from typing import Any, Iterable

from .automatic import inspect_automatic_region
from .extractor import ExtractedFunction, extract_function
from .report import write_json
from .toolchain import compiler_version, discover_toolchain, run


CPP_SUPPORT_VERSION = "bounded-cpp-regions-v2"


@dataclass(frozen=True)
class CppAdapterRequirement:
    kind: str
    reason: str
    required_boundary: str
    next_workflow: str


@dataclass(frozen=True)
class CompilationCommand:
    database: str
    index: int
    directory: str
    file: str
    arguments: tuple[str, ...]
    semantic_arguments: tuple[str, ...]
    command_sha256: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class CppFrontendError(RuntimeError):
    def __init__(self, kind: str, message: str, boundary: str, workflow: str) -> None:
        super().__init__(message)
        self.requirement = CppAdapterRequirement(kind, message, boundary, workflow)


def _sha256(value: str | bytes) -> str:
    payload = value if isinstance(value, bytes) else value.encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _json_documents(text: str) -> list[dict[str, Any]]:
    decoder = json.JSONDecoder()
    position = 0
    documents: list[dict[str, Any]] = []
    while position < len(text):
        while position < len(text) and text[position].isspace():
            position += 1
        if position >= len(text):
            break
        value, position = decoder.raw_decode(text, position)
        if isinstance(value, dict):
            documents.append(value)
    return documents


def _entry_arguments(entry: dict[str, Any]) -> list[str]:
    arguments = entry.get("arguments")
    if isinstance(arguments, list) and all(isinstance(item, str) for item in arguments):
        return list(arguments)
    command = entry.get("command")
    if isinstance(command, str):
        return shlex.split(command)
    raise CppFrontendError(
        "compile-command-adapter",
        "compilation database entry has neither a structured arguments array nor a command string",
        "one valid JSON compilation database entry",
        "repair the build export",
    )


def _resolve_entry_file(entry: dict[str, Any]) -> Path:
    directory = Path(str(entry.get("directory", "."))).resolve()
    file_path = Path(str(entry.get("file", "")))
    return (file_path if file_path.is_absolute() else directory / file_path).resolve()


def _semantic_arguments(arguments: list[str], source: Path, directory: Path) -> list[str]:
    result: list[str] = []
    skip_next = False
    value_flags = {"-o", "-MF", "-MT", "-MQ", "-MJ", "--serialize-diagnostics"}
    drop_flags = {"-c", "-MD", "-MMD", "-MP", "-MG", "-MM", "-M", "-fcolor-diagnostics"}
    for index, argument in enumerate(arguments[1:]):
        if skip_next:
            skip_next = False
            continue
        if argument in value_flags:
            skip_next = True
            continue
        if any(argument.startswith(prefix) and argument != prefix for prefix in ("-o", "-MF", "-MT", "-MQ", "-MJ")):
            continue
        if argument in drop_flags or argument.startswith("-Wp,-M"):
            continue
        candidate = Path(argument)
        if not argument.startswith("-"):
            resolved = (candidate if candidate.is_absolute() else directory / candidate).resolve()
            if resolved == source:
                continue
        if argument == "-fsyntax-only" or argument in {"-S", "-emit-llvm"}:
            continue
        result.append(argument)
    return result


def load_compilation_command(
    source: Path,
    compilation_database: Path,
    command_index: int | None = None,
) -> CompilationCommand:
    source = source.resolve()
    database = compilation_database.resolve()
    if database.is_dir():
        database = database / "compile_commands.json"
    if not database.exists():
        raise CppFrontendError(
            "compile-command-adapter",
            f"compilation database does not exist: {database}",
            "compile_commands.json generated by the production build",
            "Clang compilation-database adapter",
        )
    raw = json.loads(database.read_text())
    if not isinstance(raw, list):
        raise CppFrontendError(
            "compile-command-adapter",
            "compile_commands.json must contain a JSON array",
            "a JSON compilation database",
            "repair the build export",
        )
    matches = [(index, entry) for index, entry in enumerate(raw) if isinstance(entry, dict) and _resolve_entry_file(entry) == source]
    if not matches:
        raise CppFrontendError(
            "compile-command-adapter",
            f"no compilation database entry matches {source}",
            "the exact production translation-unit command",
            "regenerate compile_commands.json with CMAKE_EXPORT_COMPILE_COMMANDS=ON",
        )
    if command_index is None and len(matches) != 1:
        raise CppFrontendError(
            "compile-command-selection-adapter",
            f"{len(matches)} compilation commands match the source; select one with --command-index",
            "one concrete translation-unit configuration",
            "compile-command selection adapter",
        )
    if command_index is not None:
        selected = [item for item in matches if item[0] == command_index]
        if len(selected) != 1:
            raise CppFrontendError(
                "compile-command-selection-adapter",
                f"command index {command_index} does not identify a matching source entry",
                "a matching compilation-database index",
                "compile-command selection adapter",
            )
        index, entry = selected[0]
    else:
        index, entry = matches[0]
    directory = Path(str(entry.get("directory", "."))).resolve()
    arguments = _entry_arguments(entry)
    semantic = _semantic_arguments(arguments, source, directory)
    digest_input = json.dumps({"directory": str(directory), "file": str(source), "arguments": arguments}, sort_keys=True)
    return CompilationCommand(
        str(database), index, str(directory), str(source), tuple(arguments), tuple(semantic), _sha256(digest_input)
    )


def _walk(node: dict[str, Any]) -> Iterable[dict[str, Any]]:
    yield node
    for child in node.get("inner", []):
        if isinstance(child, dict):
            yield from _walk(child)


def _has_body(node: dict[str, Any]) -> bool:
    return any(child.get("kind") == "CompoundStmt" for child in node.get("inner", []) if isinstance(child, dict))


def _function_candidates(documents: list[dict[str, Any]], name: str) -> list[dict[str, Any]]:
    short_name = name.rsplit("::", 1)[-1]
    candidates: list[dict[str, Any]] = []
    seen: set[tuple[Any, ...]] = set()
    for document in documents:
        for node in _walk(document):
            if node.get("kind") not in {"FunctionDecl", "CXXMethodDecl"}:
                continue
            if node.get("name") != short_name or not _has_body(node):
                continue
            source_range = node.get("range", {})
            begin = source_range.get("begin", {}).get("offset")
            end = source_range.get("end", {}).get("offset")
            key = (node.get("mangledName"), begin, end, node.get("type", {}).get("qualType"))
            if key not in seen:
                seen.add(key)
                candidates.append(node)
    concrete = [item for item in candidates if item.get("mangledName")]
    return concrete or candidates


def _select_function(
    documents: list[dict[str, Any]], function: str, symbol: str | None
) -> tuple[dict[str, Any] | None, list[CppAdapterRequirement]]:
    candidates = _function_candidates(documents, function)
    if symbol:
        selected = [item for item in candidates if item.get("mangledName") == symbol]
        if len(selected) == 1:
            return selected[0], []
        return None, [CppAdapterRequirement(
            "symbol-selection-adapter",
            f"symbol {symbol!r} did not identify exactly one concrete definition",
            "one Clang-emitted mangled definition",
            "inspect candidate_symbols and select the production symbol",
        )]
    if len(candidates) != 1:
        symbols = sorted(str(item.get("mangledName") or item.get("type", {}).get("qualType")) for item in candidates)
        return None, [CppAdapterRequirement(
            "overload-selection-adapter",
            f"function name resolves to {len(candidates)} concrete definitions: {symbols}",
            "one mangled symbol selected with --symbol",
            "overload or template-instantiation adapter",
        )]
    return candidates[0], []


def _source_range(node: dict[str, Any], source_text: str) -> tuple[int, int]:
    source_range = node.get("range", {})
    begin = source_range.get("begin", {})
    end = source_range.get("end", {})
    start = begin.get("offset")
    finish = end.get("offset")
    token_length = end.get("tokLen", 1)
    if not isinstance(start, int) or not isinstance(finish, int):
        raise CppFrontendError(
            "source-range-adapter",
            "Clang AST did not provide a file-offset source range for the selected definition",
            "a definition written in the selected source file",
            "macro or generated-source adapter",
        )
    finish += int(token_length)
    if start < 0 or finish > len(source_text) or start >= finish:
        raise CppFrontendError(
            "source-range-adapter", "selected AST range is outside the source file", "a stable source range", "macro adapter"
        )
    return start, finish


def _call_names(node: dict[str, Any]) -> list[str]:
    names: list[str] = []
    for child in _walk(node):
        if child.get("kind") == "MemberExpr" and child.get("name"):
            names.append(str(child["name"]))
        referenced = child.get("referencedDecl")
        if isinstance(referenced, dict) and referenced.get("name"):
            names.append(str(referenced["name"]))
    return names


def _semantic_adapters(node: dict[str, Any], function_source: str) -> list[CppAdapterRequirement]:
    kinds = {str(item.get("kind")) for item in _walk(node)}
    adapters: list[CppAdapterRequirement] = []
    function_type = str(node.get("type", {}).get("qualType", ""))
    if "noexcept" not in function_type:
        adapters.append(CppAdapterRequirement(
            "exception-adapter", "selected function is not declared noexcept", "a no-throw isolated boundary", "exception and destructor protocol adapter"
        ))
    if kinds & {"CXXThrowExpr", "CXXTryStmt", "CXXCatchStmt"} or re.search(r"\b(?:throw|try|catch)\b", function_source):
        adapters.append(CppAdapterRequirement(
            "exception-adapter", "throwing or exception-handling behavior occurs in the target", "a no-throw kernel boundary", "exception protocol adapter"
        ))
    owning_constructions = [
        item for item in _walk(node)
        if item.get("kind") in {"CXXConstructExpr", "CXXTemporaryObjectExpr"}
        and not any(token in str(item.get("type", {}).get("qualType", "")) for token in ("std::span", "float", "double", "int", "size_t"))
    ]
    if kinds & {"CXXNewExpr", "CXXDeleteExpr"} or owning_constructions or re.search(r"\b(?:new|delete|make_unique|make_shared|unique_ptr|shared_ptr)\b", function_source):
        adapters.append(CppAdapterRequirement(
            "ownership-lifetime-adapter", "owning allocation or RAII state occurs in the target", "a non-owning bounded kernel", "ownership, destructor, and lifetime adapter"
        ))
    if "CXXThisExpr" in kinds:
        adapters.append(CppAdapterRequirement(
            "object-state-adapter", "the target reads or writes through this", "a state-independent method or explicit state projection", "class invariant and ownership adapter"
        ))
    if re.search(r"\b(?:atomic\w*|memory_order\w*|mutex|lock_guard|unique_lock|condition_variable|volatile)\b", function_source):
        adapters.append(CppAdapterRequirement(
            "memory-order-adapter", "atomic, volatile, or synchronization semantics occur in the target", "an explicit C++ memory-order contract", "concurrency protocol adapter"
        ))
    if kinds & {"GCCAsmStmt", "MSAsmStmt", "CoroutineBodyStmt", "CoawaitExpr", "CoyieldExpr"}:
        adapters.append(CppAdapterRequirement(
            "control-runtime-adapter", "inline assembly or coroutine runtime behavior occurs in the target", "a synchronous structured kernel", "runtime semantic adapter"
        ))
    allowed_calls = {"operator[]", "size", "data"}
    calls: set[str] = set()
    for item in _walk(node):
        if item.get("kind") in {"CallExpr", "CXXMemberCallExpr", "CXXOperatorCallExpr"}:
            names = _call_names(item)
            calls.add(names[0] if names else "<indirect>")
    unmodeled = sorted(calls - allowed_calls)
    if unmodeled:
        adapters.append(CppAdapterRequirement(
            "external-call-adapter", f"target contains unmodeled calls: {unmodeled}", "pure modeled calls or inlined information flow", "ExternalCall, Vulkan, OpenUSD, or library semantic adapter"
        ))
    unique: dict[str, CppAdapterRequirement] = {}
    for adapter in adapters:
        unique.setdefault(adapter.kind, adapter)
    return list(unique.values())


def _parameters(node: dict[str, Any]) -> list[dict[str, str]]:
    result: list[dict[str, str]] = []
    for child in node.get("inner", []):
        if isinstance(child, dict) and child.get("kind") == "ParmVarDecl":
            result.append({"name": str(child.get("name", "")), "type": str(child.get("type", {}).get("qualType", ""))})
    return result


def _abi_class(parameters: list[dict[str, str]]) -> str | None:
    types = [re.sub(r"\s+", " ", item["type"]).strip() for item in parameters]
    if len(types) == 3:
        first = types[0].replace(" ", "")
        second = types[1].replace(" ", "")
        if first == "float*" and second in {"constfloat*", "floatconst*"} and types[2] in {"size_t", "std::size_t", "unsigned long"}:
            return "pointer-view"
    if len(types) == 2 and "std::span<float" in types[0] and "std::span<const float" in types[1]:
        return "span-view"
    compact = [item.replace(" ", "") for item in types]
    if len(compact) == 2 and compact[0] in {"std::vector<float>&", "vector<float>&"} and compact[1] in {
        "conststd::vector<float>&", "std::vector<float>const&", "constvector<float>&"
    }:
        return "vector-view"
    return None


def _canonical_kernel(function_source: str, node: dict[str, Any], abi: str) -> tuple[str, ExtractedFunction, dict[str, str]]:
    name = str(node.get("name"))
    extraction_source = re.sub(rf"\b{re.escape(name)}\s*<[^>{{}}]+>\s*\(", f"{name}(", function_source, count=1)
    extracted = extract_function(extraction_source, name)
    parameters = _parameters(node)
    mapping: dict[str, str] = {}
    body = extracted.body
    canonical_names = ("dst", "src", "n") if abi == "pointer-view" else ("dst", "src")
    for parameter, canonical in zip(parameters, canonical_names):
        original = parameter["name"]
        if not original:
            raise ValueError("all bounded kernel parameters must be named")
        mapping[canonical] = original
        if original != canonical:
            body = re.sub(rf"\b{re.escape(original)}\b", canonical, body)
    body = body.replace("std::size_t", "size_t")
    if abi in {"span-view", "vector-view"}:
        body = re.sub(r"(?:const\s+)?size_t\s+n\s*=\s*src\.size\s*\(\s*\)\s*;", "", body)
        body = re.sub(r"src\.size\s*\(\s*\)", "n", body)
        body = re.sub(r"dst\.size\s*\(\s*\)", "n", body)
    if re.search(r"\.(?:size|data)\s*\(", body):
        raise ValueError("container access outside the modeled span extent pattern remains after isolation")
    if re.search(r"\b(?:class|typename)\b", body):
        raise ValueError("unresolved template syntax remains in isolated body")
    source = "#include <stddef.h>\n\nvoid transform(float *dst, const float *src, size_t n) {\n" + body.strip() + "\n}\n"
    return source, extract_function(source, "transform"), mapping


def _emit_ast(command: CompilationCommand, source: Path, function: str, out_dir: Path) -> tuple[list[dict[str, Any]], Path]:
    tc = discover_toolchain()
    if tc.compiler_kind != "clang":
        raise CppFrontendError("clang-frontend-adapter", "C++ extraction requires Clang", "Clang semantic AST", "install the pinned Clang toolchain")
    path = out_dir / "target.ast.json"
    filter_name = function.rsplit("::", 1)[-1]
    cmd = [
        tc.compiler, *command.semantic_arguments,
        "-Xclang", "-ast-dump=json", "-Xclang", "-ast-dump-filter", "-Xclang", filter_name,
        "-fsyntax-only", str(source),
    ]
    result = run(cmd, cwd=Path(command.directory), timeout=180)
    if result.returncode != 0:
        raise CppFrontendError(
            "clang-frontend-adapter", f"Clang AST extraction failed: {(result.stdout + result.stderr)[-2000:]}",
            "a Clang-compatible production command", "compile-command or source adapter",
        )
    path.write_text(result.stdout)
    documents = _json_documents(result.stdout)
    if not documents:
        raise CppFrontendError("function-extraction-adapter", f"Clang found no declarations matching {function!r}", "one concrete definition", "qualified-name adapter")
    return documents, path


def _normalize_ir_function(text: str, symbol: str) -> str:
    escaped = re.escape(symbol)
    lines: list[str] = []
    keep = False
    depth = 0
    for line in text.splitlines():
        if line.startswith("define ") and re.search(rf'@(?:"{escaped}"|{escaped})\(', line):
            keep = True
            depth = line.count("{") - line.count("}")
        if keep:
            cleaned = re.sub(r",\s*![A-Za-z0-9_.]+\s+![0-9]+", "", line)
            cleaned = re.sub(rf'@(?:"{escaped}"|{escaped})\(', "@transform(", cleaned)
            lines.append(cleaned)
            if line != lines[0]:
                depth += line.count("{") - line.count("}")
            if depth == 0:
                break
    if not lines:
        raise CppFrontendError(
            "ir-symbol-adapter", f"selected symbol {symbol!r} is absent from emitted LLVM IR",
            "an emitted concrete definition", "force concrete template instantiation or disable dead stripping",
        )
    return "\n".join(lines) + "\n"


def _emit_cpp_ir(command: CompilationCommand, source: Path, symbol: str, out_dir: Path) -> dict[str, Any]:
    tc = discover_toolchain()
    raw = out_dir / "target.production.ll"
    analysis_raw = out_dir / "target.analysis.ll"
    normalized = out_dir / "target.normalized.ll"
    production_flags = list(command.semantic_arguments)
    production_result = run(
        [tc.compiler, *production_flags, "-S", "-emit-llvm", str(source), "-o", str(raw)],
        cwd=Path(command.directory), timeout=180,
    )
    if production_result.returncode != 0:
        raise CppFrontendError(
            "compiler-adapter", f"production C++ LLVM IR emission failed: {(production_result.stdout + production_result.stderr)[-2000:]}",
            "Clang LLVM IR for the production command", "compiler flag adapter",
        )
    analysis_flags = [*command.semantic_arguments, "-O1", "-fno-vectorize", "-fno-slp-vectorize", "-fno-unroll-loops"]
    analysis_result = run(
        [tc.compiler, *analysis_flags, "-S", "-emit-llvm", str(source), "-o", str(analysis_raw)],
        cwd=Path(command.directory), timeout=180,
    )
    if analysis_result.returncode != 0:
        raise CppFrontendError(
            "compiler-adapter", f"analysis C++ LLVM IR emission failed: {(analysis_result.stdout + analysis_result.stderr)[-2000:]}",
            "Clang analysis IR for the production command", "compiler flag adapter",
        )
    retention_mode = "production-ir"
    try:
        normalized_text = _normalize_ir_function(raw.read_text(errors="replace"), symbol)
    except CppFrontendError:
        try:
            normalized_text = _normalize_ir_function(analysis_raw.read_text(errors="replace"), symbol)
            retention_mode = "analysis-ir-symbol-retention"
        except CppFrontendError:
            retention_flags = [*analysis_flags, "-fno-inline"]
            retention_result = run(
                [tc.compiler, *retention_flags, "-S", "-emit-llvm", str(source), "-o", str(analysis_raw)],
                cwd=Path(command.directory), timeout=180,
            )
            if retention_result.returncode != 0:
                raise
            normalized_text = _normalize_ir_function(analysis_raw.read_text(errors="replace"), symbol)
            retention_mode = "no-inline-analysis-symbol-retention"
    normalized.write_text(normalized_text)
    return {
        "compiler": tc.compiler,
        "compiler_version": compiler_version(tc.compiler),
        "raw_ir": str(raw),
        "raw_ir_sha256": _sha256(raw.read_bytes()),
        "production_flags": production_flags,
        "analysis_ir": str(analysis_raw),
        "analysis_ir_sha256": _sha256(analysis_raw.read_bytes()),
        "analysis_flags": analysis_flags,
        "normalized_ir": str(normalized),
        "normalized_ir_sha256": _sha256(normalized.read_bytes()),
        "symbol_retention_mode": retention_mode,
    }


def _prove_span_adapter(out_dir: Path) -> dict[str, Any]:
    smt_path = out_dir / "adapter-extents.smt2"
    try:
        import z3
    except ImportError:
        smt_path.write_text("; z3 unavailable\n")
        return {"status": "UNAVAILABLE", "method": "z3", "smt2": str(smt_path)}
    n, src_size, dst_size, index = z3.Ints("n src_size dst_size index")
    solver = z3.Solver()
    solver.add(n >= 0, src_size == n, dst_size >= n)
    solver.add(index >= 0, index < n)
    solver.add(z3.Or(index >= src_size, index >= dst_size))
    result = solver.check()
    smt_path.write_text("; Counterexample query for span adapter extent safety\n" + solver.to_smt2())
    return {
        "status": "PROVED" if result == z3.unsat else "FAILED",
        "method": "z3-int",
        "result": str(result),
        "property": "dst.size() >= src.size() makes every generated access in both borrowed views in-bounds",
        "scope": "adapter extent and loop-index mapping only; not C++ ownership, publication, exceptions, or external protocols",
        "smt2": str(smt_path),
    }


def _replacement_body(abi: str, mapping: dict[str, str], helper_name: str) -> str:
    dst = mapping["dst"]
    src = mapping["src"]
    if abi == "pointer-view":
        return "{\n    " + helper_name + f"({dst}, {src}, {mapping['n']});\n}}"
    return "{\n    " + helper_name + f"({dst}.data(), {src}.data(), {src}.size());\n}}"


def _regenerate_cpp(
    source_text: str,
    source_range: tuple[int, int],
    function_source: str,
    node: dict[str, Any],
    abi: str,
    mapping: dict[str, str],
    kernel_source: str,
) -> tuple[str, str, dict[str, Any]]:
    local_open = function_source.find("{")
    if local_open < 0:
        raise ValueError("selected function has no source body")
    local_close = function_source.rfind("}")
    if local_close <= local_open:
        raise ValueError("selected function has an invalid source body")
    global_open = source_range[0] + local_open
    global_close = source_range[0] + local_close
    helper_name = "__vladder_kernel_" + _sha256(function_source)[:12]
    kernel = extract_function(kernel_source, "transform").renamed(helper_name)
    kernel = re.sub(r"\bsize_t\b", "std::size_t", kernel)
    replacement_body = _replacement_body(abi, mapping, helper_name)
    replaced = source_text[:global_open] + replacement_body + source_text[global_close + 1 :]
    generated = "#include <cstddef>\n\n" + kernel + "\n\n" + replaced
    context = {
        "helper": helper_name,
        "abi": abi,
        "mapping": mapping,
        "body_start": global_open,
        "body_end": global_close + 1,
        "source_sha256": _sha256(source_text),
        "function_source_sha256": _sha256(function_source),
    }
    return generated, replacement_body + "\n", context


def _compile_regenerated(command: CompilationCommand, original: Path, generated: Path) -> dict[str, Any]:
    tc = discover_toolchain()
    result = run(
        [tc.compiler, *command.semantic_arguments, "-iquote", str(original.parent), "-fsyntax-only", str(generated)],
        cwd=Path(command.directory), timeout=180,
    )
    return {
        "status": "pass" if result.returncode == 0 else "fail",
        "returncode": result.returncode,
        "stderr": result.stderr[-4000:],
        "compiler": tc.compiler,
    }


def inspect_cpp_region(
    source: Path,
    function: str,
    compilation_database: Path,
    out_dir: Path,
    *,
    symbol: str | None = None,
    command_index: int | None = None,
) -> dict[str, Any]:
    source = source.resolve()
    out_dir = out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    source_text = source.read_text()
    report: dict[str, Any] = {
        "status": "adapter_required",
        "supported": False,
        "support_version": CPP_SUPPORT_VERSION,
        "language": "c++",
        "source": str(source),
        "source_sha256": _sha256(source_text),
        "function": function,
        "requested_symbol": symbol,
        "proof_classification": "unclassified",
        "adapters": [],
        "artifacts": {},
    }
    try:
        command = load_compilation_command(source, compilation_database, command_index)
        report["compile_command"] = command.to_dict()
        documents, ast_path = _emit_ast(command, source, function, out_dir)
        report["artifacts"]["ast"] = str(ast_path)
        candidates = _function_candidates(documents, function)
        report["candidate_symbols"] = [
            {"symbol": item.get("mangledName"), "type": item.get("type", {}).get("qualType"), "kind": item.get("kind")}
            for item in candidates
        ]
        node, selection_adapters = _select_function(documents, function, symbol)
        if selection_adapters:
            report["adapters"] = [asdict(item) for item in selection_adapters]
            write_json(out_dir / "cpp-support.json", report)
            return report
        assert node is not None
        selected_range = _source_range(node, source_text)
        function_source = source_text[selected_range[0] : selected_range[1]]
        selected_ast = out_dir / "selected-function.ast.json"
        write_json(selected_ast, node)
        report["artifacts"]["selected_ast"] = str(selected_ast)
        parameters = _parameters(node)
        abi = _abi_class(parameters)
        report["selection"] = {
            "kind": node.get("kind"),
            "name": node.get("name"),
            "symbol": node.get("mangledName"),
            "type": node.get("type", {}).get("qualType"),
            "parameters": parameters,
            "source_range": list(selected_range),
            "function_sha256": _sha256(function_source),
        }
        adapters = _semantic_adapters(node, function_source)
        if abi is None:
            adapters.append(CppAdapterRequirement(
                "abi-adapter",
                "selected C++ definition is outside the pointer-view and dynamic std::span<float> support classes",
                "(float*, const float*, size_t) or (std::span<float>, std::span<const float>)",
                "container, ownership, or operator contract adapter",
            ))
        if not node.get("mangledName"):
            adapters.append(CppAdapterRequirement(
                "template-instantiation-adapter", "selected template has no concrete emitted symbol", "one explicit concrete instantiation or specialization", "template realization adapter"
            ))
        if adapters:
            report["adapters"] = [asdict(item) for item in adapters]
            write_json(out_dir / "cpp-support.json", report)
            return report
        assert abi is not None
        production_ir = _emit_cpp_ir(command, source, str(node["mangledName"]), out_dir)
        report["production_ir"] = production_ir
        kernel_source, _, mapping = _canonical_kernel(function_source, node, abi)
        kernel_path = out_dir / "isolated-kernel.c"
        kernel_path.write_text(kernel_source)
        report["artifacts"]["isolated_kernel"] = str(kernel_path)
        kernel_support = inspect_automatic_region(kernel_path, "transform", out_dir / "kernel-analysis")
        report["kernel_support"] = kernel_support.to_dict()
        if not kernel_support.supported:
            report["adapters"] = [asdict(CppAdapterRequirement(
                "kernel-shape-adapter",
                kernel_support.adapters[0].reason if kernel_support.adapters else "isolated kernel is outside the bounded support matrix",
                "one bounded-regions-v1 compatible loop",
                "operator or project-specific kernel adapter",
            ))]
            write_json(out_dir / "cpp-support.json", report)
            return report
        adapter_proof = _prove_span_adapter(out_dir) if abi in {"span-view", "vector-view"} else {
            "status": "PROVED",
            "method": "identity-abi",
            "property": "the isolated kernel retains the original pointer and extent parameters",
            "scope": "ABI mapping only; caller pointer validity remains a contract precondition",
        }
        contract = {
            "schema_version": "vladder-cpp-adapter-contract-v1",
            "abi_class": abi,
            "preconditions": ["dst and src denote valid ranges for n elements"] if abi == "pointer-view" else [
                "dst.size() >= src.size()", "both views and their storage remain alive and stable for the call", "baseline alias behavior is preserved"
            ],
            "postconditions": ["the wrapper invokes the proved kernel exactly once", "n equals the source extent"],
            "excluded_claims": ["RAII protocol equivalence", "exception equivalence", "concurrency equivalence", "external API equivalence"],
            "proof": adapter_proof,
        }
        contract_path = out_dir / "adapter-contract.json"
        write_json(contract_path, contract)
        generated, replacement_body, context = _regenerate_cpp(
            source_text, selected_range, function_source, node, abi, mapping, kernel_source
        )
        generated_path = out_dir / "regenerated.cpp"
        body_path = out_dir / "replacement-body.inc"
        context_path = out_dir / "cpp-context.json"
        generated_path.write_text(generated)
        body_path.write_text(replacement_body)
        context.update({"source": str(source), "source_range": list(selected_range), "function": function, "symbol": node["mangledName"]})
        write_json(context_path, context)
        compile_report = _compile_regenerated(command, source, generated_path)
        report["artifacts"].update({
            "adapter_contract": str(contract_path), "regenerated_cpp": str(generated_path),
            "replacement_body": str(body_path), "context": str(context_path),
        })
        report["verification"] = {"adapter": adapter_proof, "regenerated_compile": compile_report}
        if adapter_proof.get("status") != "PROVED" or compile_report["status"] != "pass":
            report["adapters"] = [asdict(CppAdapterRequirement(
                "adapter-verification-failure", "generated C++ adapter failed its proof or compiler check", "a proved and compiling bridge", "manual adapter repair"
            ))]
            write_json(out_dir / "cpp-support.json", report)
            return report
        provenance = {
            "schema_version": "vladder-cpp-provenance-v1",
            "source_sha256": report["source_sha256"],
            "function_sha256": report["selection"]["function_sha256"],
            "compile_command_sha256": command.command_sha256,
            "ast_sha256": _sha256(selected_ast.read_bytes()),
            "production_ir_sha256": production_ir["normalized_ir_sha256"],
            "production_module_sha256": production_ir["raw_ir_sha256"],
            "analysis_module_sha256": production_ir["analysis_ir_sha256"],
            "isolated_kernel_sha256": _sha256(kernel_path.read_bytes()),
            "regenerated_cpp_sha256": _sha256(generated_path.read_bytes()),
        }
        provenance_path = out_dir / "provenance.json"
        write_json(provenance_path, provenance)
        report["artifacts"]["provenance"] = str(provenance_path)
        report.update({
            "status": "supported", "supported": True, "abi_class": abi,
            "proof_classification": "kernel_isolated_adapter_proved",
            "exactness": "E1-ordered",
            "proof_layers": [
                "Clang semantic AST legality", "production compile-command LLVM provenance",
                "Z3 adapter extent proof", "isolated-kernel structural legality",
                "Z3 loop and memory proof required for each candidate",
                "Alive2 isolated-kernel refinement required for each candidate",
                "differential execution required for each candidate", "generated C++ compile and source identity",
            ],
            "claim_boundary": "local kernel refinement plus bounded adapter obligations; owning C++ and external protocols are not proved",
        })
    except (CppFrontendError, ValueError, OSError, json.JSONDecodeError) as error:
        if isinstance(error, CppFrontendError):
            adapter = error.requirement
        else:
            adapter = CppAdapterRequirement("cpp-extraction-adapter", str(error), "one supported bounded C++ definition", "specialized C++ adapter")
        report["adapters"] = [asdict(adapter)]
    write_json(out_dir / "cpp-support.json", report)
    return report


def regenerate_cpp_with_kernel(cpp_report: Path, kernel_source: Path, output: Path) -> dict[str, Any]:
    report = json.loads(cpp_report.read_text())
    if report.get("status") != "supported":
        return {"status": "fail", "reason": "C++ isolation report is not supported"}
    source = Path(report["source"])
    source_text = source.read_text()
    if _sha256(source_text) != report.get("source_sha256"):
        return {"status": "fail", "reason": "production source changed after C++ extraction; recapture is required"}
    selection = report["selection"]
    start, end = selection["source_range"]
    function_source = source_text[start:end]
    ast = json.loads(Path(report["artifacts"]["selected_ast"]).read_text())
    context = json.loads(Path(report["artifacts"]["context"]).read_text())
    generated, replacement_body, _ = _regenerate_cpp(
        source_text, (start, end), function_source, ast, report["abi_class"], context["mapping"], kernel_source.read_text()
    )
    output.write_text(generated)
    body_path = output.with_suffix(".body.inc")
    body_path.write_text(replacement_body)
    command_raw = report["compile_command"]
    command = CompilationCommand(
        command_raw["database"], command_raw["index"], command_raw["directory"], command_raw["file"],
        tuple(command_raw["arguments"]), tuple(command_raw["semantic_arguments"]), command_raw["command_sha256"],
    )
    compile_report = _compile_regenerated(command, source, output)
    return {
        "status": "pass" if compile_report["status"] == "pass" else "fail",
        "source": str(output), "replacement_body": str(body_path), "compile": compile_report,
        "kernel_sha256": _sha256(kernel_source.read_bytes()), "source_sha256": _sha256(output.read_bytes()),
    }


def optimize_cpp_region(
    source: Path,
    function: str,
    compilation_database: Path,
    out_dir: Path,
    *,
    symbol: str | None = None,
    command_index: int | None = None,
    n: int = 1 << 18,
    reps: int = 25,
    inner: int = 8,
    cpu: int = 0,
    minimum_speedup_pct: float = 1.0,
) -> tuple[int, dict[str, Any]]:
    out_dir = out_dir.resolve()
    isolation_dir = out_dir / "isolation"
    report = inspect_cpp_region(source, function, compilation_database, isolation_dir, symbol=symbol, command_index=command_index)
    result: dict[str, Any] = {"status": "adapter_required", "isolation": report}
    if report.get("status") != "supported":
        write_json(out_dir / "cpp-optimization.json", result)
        return 2, result
    kernel_dir = out_dir / "kernel-optimization"
    from .cli import main
    return_code = main([
        "region", "optimize", "--source", report["artifacts"]["isolated_kernel"], "--function", "transform",
        "--out-dir", str(kernel_dir), "--n", str(n), "--reps", str(reps), "--inner", str(inner),
        "--cpu", str(cpu), "--min-speedup-pct", str(minimum_speedup_pct),
    ])
    perf_path = kernel_dir / "perf.json"
    perf = json.loads(perf_path.read_text()) if perf_path.exists() else {}
    winner = perf.get("winner") if isinstance(perf.get("winner"), dict) else {}
    alive2 = winner.get("alive2") if isinstance(winner.get("alive2"), dict) else {}
    candidate_proved = alive2.get("status") == "correct" and winner.get("status") == "PASS"
    result = {
        "status": "complete" if return_code == 0 else "kernel_workflow_failed",
        "isolation": report,
        "kernel_report": str(perf_path),
        "kernel_return_code": return_code,
        "promotion": perf.get("promotion"),
        "proof_classification": "kernel_proved_adapter_bounded" if candidate_proved else "kernel_candidate_not_proved",
    }
    optimized = kernel_dir / "optimized.c"
    if optimized.exists() and perf.get("promotion", {}).get("promotable"):
        realization = regenerate_cpp_with_kernel(isolation_dir / "cpp-support.json", optimized, out_dir / "optimized.cpp")
        result["realization"] = realization
        if realization["status"] != "pass":
            result["status"] = "realization_failed"
            return_code = 1
    write_json(out_dir / "cpp-optimization.json", result)
    return return_code, result
